# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citrusresponse',
            name='transaction_name',
            field=models.CharField(default='Saurav Biswas', max_length=255),
        ),
    ]
