# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_citrusresponse_transaction_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citrusresponse',
            name='transaction_name',
        ),
    ]
