# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitrusResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_string', models.TextField()),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('data_string', models.TextField()),
            ],
        ),
    ]
