# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaseUser',
            new_name='FaseClient',
        ),
    ]
