# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20161126_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, unique=True)),
                ('app_secret_key', models.CharField(max_length=100, unique=True)),
                ('app_encrypted_key', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 11, 26, 5, 42, 32, 622343, tzinfo=utc))),
                ('description', models.TextField(default=b'A simple android app for fase')),
            ],
        ),
    ]
